<?php
	require_once($ROOT.'libs/domain/RequestManager.php');
	require_once ($ROOT.'libs/dao/DAOFactory.php');
	require_once ($ROOT.'libs/dao/DAO.php');
	require_once ($ROOT.'libs/dao/V1Dao.php');
	require_once ($ROOT.'libs/dao/delegates/UpdateDomain.php');
	require_once ($ROOT.'libs/dao/delegates/ListDomains.php');
	require_once ($ROOT.'libs/dao/delegates/Cache.php');
	require_once ($ROOT.'libs/dao/delegates/DeleteProject.php');
	require_once ($ROOT.'libs/dao/delegates/GetProject.php');
	require_once ($ROOT.'libs/dao/delegates/GetProjects.php');
	require_once ($ROOT.'libs/dao/delegates/UpdateProject.php');
	require_once ($ROOT.'libs/dao/delegates/GetConfig.php');
	require_once ($ROOT.'libs/dao/delegates/UpdateConfig.php');
	require_once ($ROOT.'libs/dao/delegates/DeleteConfig.php');
	require_once ($ROOT.'libs/dao/delegates/GetConfigs.php');
	require_once ($ROOT.'libs/dao/delegates/GetProjectAssets.php');
	require_once ($ROOT.'libs/dao/delegates/GetModifedProjectAssets.php');
	require_once ($ROOT.'libs/dao/dto/Domain.php');
	require_once ($ROOT.'libs/dao/dto/CustomAwsResponse.php');
	require_once ($ROOT.'libs/dao/dto/CustomAWSError.php');
	require_once ($ROOT.'libs/dao/dto/Focus360Base.php');
	require_once ($ROOT.'libs/dao/dto/Project.php');
	require_once ($ROOT.'libs/dao/dto/Config.php');
	require_once ($ROOT.'libs/dao/dto/ProjectAsset.php');
	require_once ($ROOT.'libs/util/DataValidator.php' );
	require_once ($ROOT.'libs/util/FileUtils.php' );
	require_once ($ROOT.'libs/dao/aws143/sdk.class.php');
	require_once ($ROOT.'libs/dao/AwsUtils.php');
	define('PROJECTS_DOMAIN', 'focus360_projects_v1');
	define('CONFIG_DOMAIN', 'focus360_config_v1');
	define('CONFIG_LIST_CACHE_KEY', 'focus360_configList');
	define('PROJECT_LIST_CACHE_KEY', 'focus360_projectList');
	define('PROJECT_JSON_CHUNK_PREFIX', 'projectJSON_');
	define('BASE_ASSET_DIRECTORY', $ROOT . 'assets/');
	//define('BASE_URL', 'http://localhost/focus360/');
	//define('BASE_URL', 'http://www.focus360.net/focus360API/');
	define('BASE_URL', 'http://dev.ryanguthrie.com/focus360/');
	define('SINGLE_FAMILY_DIRECTORY', 'SingleFamilySiteMaps');
	define('MULTI_FAMILY_DIRECTORY', 'MultiFamilySiteMaps');
	define('FLOOR_PLAN_DIRECTORY', 'FloorPlans');
	define('BUILDING_PLATE_DIRECTORY', 'BuildingPlates');
	define('EXTERIORS_DIRECTORY', 'Exteriors');
	define('ILLUSTRATIONS_DIRECTORY', 'Illustrations');
	define('INTERIORS_DIRECTORY', 'Interiors');
	define('VIDEOS_DIRECTORY', 'Videos');
	define('PHOTOS_DIRECTORY', 'Photos');
	define('VACINITY_MAPS_DIRECTORY', 'VacinityMaps');
?>
