# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.core.mail import send_mail
import smtplib, sys

def index(request):
    #return HttpResponse("Hello, world. You're at the poll index.")
    return render_to_response('default.html', {'latest_poll_list': "balls"})

def contact(request):
	return render_to_response('contact.html',{})


def send_email(request):
	msg = "Email sent"
	postvalues = request.POST
	fullmsg = "Form details: \n"
	for param in postvalues:
		fullmsg += param+": "+str(postvalues[param])+"\n"
	#poststring = str(postvalues)
	#return HttpResponse(fullmsg)
	try:
		send_mail('Message from RyanGuthrie.com', "You got an email from RyanGuthrie.com: \n"+fullmsg, 'ryang@ryanguthrie.com',
			['ryan@ryanguthrie.com'], fail_silently=False)
	except:
		z = str(sys.exc_info()[1])
		msg = "SMTPException when sending email \n"+z
	#return render_to_resposne("contact.html",{'error_email':msg})
	return HttpResponse(msg)

def send_quote(request):
	msg = "Quotes sent"
	postvalues = request.POST
	fullmsg = "Form details: \n"
	for param in postvalues:
		fullmsg += param+": "+str(postvalues[param])+"\n"
	try:
		send_mail('Quote from RyanGuthrie.com', "You got an quote from RyanGuthrie.com: \n"+fullmsg, 'ryang@ryanguthrie.com',
			['ryan@ryanguthrie.com'], fail_silently=False)
	except:
		z = str(sys.exc_info()[1])
		msg = "SMTPException when sending email \n"+z
	return HttpResponse(msg)

def about(request):
	return render_to_response('about.html',{})

def resume(request):
	return render_to_response('resume.html',{})

def services(request):
	return render_to_response('services.html',{})

def portfolio(request):
	fake_model = [
		{
			'imgSrc': '/site_media/images/portfolio/rg_icon.png',
			'imgTitle':'RyanGuthrie.com',
			'tag':'rr',
			'title':'RyanGuthrie.com',
			'images': [{
				"src":'/site_media/images/portfolio/rg_main1.png',
				"thumbSrc":'/site_media/images/portfolio/rg_main1_thumb.png',
				"alt":'RyanGuthrie.com Home Page',
				},
				{
				"src":'/site_media/images/portfolio/rg_contact.png',
				"thumbSrc":'/site_media/images/portfolio/rg_contact_thumb.png',
				"alt":'RyanGuthrie.com Portfolio',
				}],
			'info': "<blockquote>This site is a proof of concept as well as my own portfolio. It is built with a solid framework \
				that can be used to power everything from a brochure style site, to a fully interactive web 2.0 application.\
				The site was fully coded and designed by me, with logo and some graphics added by <a href='http://www.jho-tan.com'>Jho</a>.\
				</blockquote>\
				<b>Languages Used:</b> Perl, Javascript, HTML/CSS<br>\
				<b>Server Side:</b> The server is running a modified Catalyst application in Perl, with hooks to a MySQL database<br>\
				<b>User Interface:</b>The Catalyst engine serves HTML templates that includes the jQuery Javascript library in order to generate <br>\
				many of the interactive elements on this site. These include the portfolio slider, image viewer, drop down menus and interactive contact form.<br>\
				The side bar is a live xml stream of my public Google Buzz feed. \
				<b>Graphics:</b>The fish logo and top menu icons were made by Jho. The rest were created and modified by me using Photoshop<br>\
				"
		},
		{
			'imgSrc': '/site_media/images/portfolio/freephoto_icon.png',
			'imgTitle':'Free Photo Project',
			'tag':'freephoto',
			'title':'Free Photo Project.org',
			'images': [{
				"src":'/site_media/images/portfolio/freephoto_big.jpg',
				"thumbSrc":'/site_media/images/portfolio/freephoto_big_thumb.png',
				"alt":'Free Photo Project home page',
				}],
			'info': """<blockquote>Free Photo Project is a non profit that takes free family and portrait photos for the homeless
			or otherwise disadvantaged. I took the initial design as a single PhotoShop file and turned it into a fully functional wordpress site.
			The site includes several custom plugins with options in the admin panel for easy configuration. 
				</blockquote>
				<b>Languages Used:</b> PHP, Javascript, HTML/CSS<br>
				<b>Server Side:</b> The site runs of Wordpress, a PHP CMS on top of a Linux server with MySQL database<br>
				<b>User Interface:</b>The interface is made as a custom Wordpress theme that uses several plugins to provide rich content 
				<b>Graphics:</b>The design file was generated by Limelight Dept as a PSD file which I then turned into useable web graphics<br>
				"""
		},
		{
			"imgSrc":"/site_media/images/portfolio/jj_icon.png",
			"imgTitle":"Jiu Jitsu",
			"tag":"bjj",
			"title":"Heitor Abrahao Jiu Jitsu",
			"images": [{
	                               "src":'/site_media/images/portfolio/jj_main.png',
	                                "thumbSrc":'/site_media/images/portfolio/jj_main_thumb.png',
	                                "alt":'Abrahao Jiu Jitsu Home Page',
	                        },{
	                                "src":'/site_media/images/portfolio/jj_gal.png',                                
									"thumbSrc":'/site_media/images/portfolio/jj_gal_thumb.png',
	                                "alt":'Abrahao Jiu Jitsu Photo Gallery',
	                        },{
									"src":'/site_media/images/portfolio/jj_media.png',
									"thumbSrc":'/site_media/images/portfolio/jj_media_thumb.png',
									"alt":'Restyled Photo and Video Gallery',
							},{
									"src":'/site_media/images/portfolio/jj_signup.png',
									"thumbSrc":'/site_media/images/portfolio/jj_signup_thumb.png',
									"alt":'Online Video Lessons - signup form',
							}],
			"info" : """<blockquote>Abrahao Jiu Jitsu is a media heavy site to promote Heitor Abrahao's Jiu Jitsu School in Eugene, Oregon. 
				It is handcoded html/css, with a flash image gallery. All design is by me, with graphics used a mixture of custom graphics 
				and existing photos. It is currently being revamped to include an easy management panel, interactive media 
				and a full subscription based video tutorial system integrated with Paypal.</blockquote>
				<b>Languages Used:</b>HTML/CSS, Javascript, Perl/Catalyst and a custom Flash player as well<br>
				""",
		},
		{
                "imgSrc":"/site_media/images/portfolio/ww_icon.png",
                "imgTitle":"WoWWizards",
                "tag":"ww",
                "title":"WoW Wizards News and Database",
                "images": [{
					"src":'/site_media/images/portfolio/ww_main.png',
					"thumbSrc":'/site_media/images/portfolio/ww_main_thumb.png',
					"alt":'WoWWizards Main Page',
					},{                               
					"src":'/site_media/images/portfolio/ww_sig.png', 
					"thumbSrc":'/site_media/images/portfolio/ww_sig_thumb.png',
					"alt":'WoWWizards Signature Generator',
                    }],
			"info" : """<blockquote>WoWWizards is a database and information site for players of the popular online game 
			<a href='http://www.worldofwarcraft.com'>World of Warcraft</a>. It includes a database of in-game items, commenting system, 
			news parser, and a modified signature generator. It is written in PHP, running of the <a href='http://cakephp.org'>Cake</a> 
			framework, with heavy use of MySQL. The news scraper and sitemap generator are both written in Perl. The signature generator 
			is easily the most popular feature of the site. It was originally a free opensource php app, but has been heavily modified since
			to include new features and fix many issues that come up as the game changes their data sources.
			</blockquote>
			""",
	  	},
	  	{
            "imgSrc":"/site_media/images/portfolio/cloud_icon.png",
            "imgTitle":"CloudPillow",
            "tag":"cloud",
            "title":"CloudPillow Multi-Lingual Books",
            "images": [{
				"src":'/site_media/images/portfolio/cloud_main.png',
				"thumbSrc":'/site_media/images/portfolio/cloud_main_thumb.png',
				"alt":'CloudPillow Main Design',
				}],
			"info" : """<blockquote>Cloud Pillow Books is an upcoming children's book publisher with a focus on multiple languages. This is 
			currently a prototype design by me, with fully custom graphics. It uses google calendar for an event schedule, and a drop down 
			language bar to welcome a wide international audience.</blockquote>
			""",
	        },
		{
			"imgSrc":"/site_media/images/portfolio/thewas_icon.png",
            "imgTitle":"The WAS",
            "tag":"was",
            "title":"Webcomic Artists Society",
            "images": [{
				"src":'/site_media/images/portfolio/thewas_main.png',
				"thumbSrc":'/site_media/images/portfolio/thewas_main_thumb.png',
				"alt":'WAS customized forum',
				},{
				"src":'/site_media/images/portfolio/thewas_paintgo.png',
				"thumbSrc":'/site_media/images/portfolio/thewas_paintgo_thumb.png',
				"alt":'A custom paint forum thread',
				},{
				"src":'/site_media/images/portfolio/thewas_waspaint.png',
				"thumbSrc":'/site_media/images/portfolio/thewas_waspaint_thumb.png',
				"alt":'Custom Flash painting app',
				}],
			"info" : """<blockquote>The WAS is a small community of artists, from the occasional hobbyists to talented professionals. I host and run the site, focused
			on a heavily modified phpBB installation. Mods include automatic archiving of any images posted, custom irc based chat room, user webspace, embedded messaging
			similar to facebook or google chat, and a custom Flash based paint program that saves to the server and can be used to reply in specific paint threads.</blockquote>
			""",
		},
		{
			"imgSrc":"/site_media/images/portfolio/reddittube_icon.png",
	                "imgTitle":"Reddit Tube",
	                "tag":"reddittube",
	                "title":"Reddit Tube - reddit/youtube music player",
	                "images": [{
						"src":'/site_media/images/portfolio/reddittube_main.png',
						"thumbSrc":'/site_media/images/portfolio/reddittube_main_thumb.png',
						"alt":'Music player main page',
						}],
			"info" : """<blockquote>Reddittube is a single page site used to play music which redditors suggest. A server script parses a specific reddit comment thread
			for any youtube links every 5 minutes. It stores information about the containing post and the link in memcache. The page then requests the cached list and 
			uses jQuery to generate a scrollable, sortable playlist. Options include playing a random track, viewing song details, playing through the playlist or 
			only playing a single track. Plans include multiple playlists culled from various sources.<br>
			<a href='http://thegupstudio.com/reddittube'>Listen to Reddit Tube</a></blockquote>
			""",	
			
		}
	]	
	return render_to_response('showcase.html',{
		'portfolio':fake_model, 
		'portfolio_size': len(fake_model)*115
		})

def projects(request):
	fake_model = [
			{       "title":'Picture of the Moment',
                "short":'Automatically  Generated Photo Gallery',
                "imgSrc":'/site_media/images/project/pom_thumb.png',
				"cat":'Tools',
				"tag":"pom",
                "info":"""PoM is a php program designed to be able to be dropped on any 
				php capable server and automatically create and maintain an image gallery. You simply 
				tell it what directory to monitor, how many images per page, and where to store thumbnails. 
				It will automatically detect any new images that are uploaded and create an appropriate thumbnail. 
				You can either use an existing css sheet to style the gallery, or change the style within 
				the source code.<br>
				<b>Technologies:</b> PHP, GD library""",
        },
        {       "title":'Repulsor',
                "short":'Arcade style space shooter',
				"cat":'Games',
				"tag":"repulsor",
                "imgSrc":'/site_media/images/project/rep_ship.png',
                "info":"""Small, arcade style video game originally developed for the 72 Hour Game Dev Competition. 
				It was developed by a team of 3: Kevin (programming), Joe (art), and myself (programming), using the PyGame 
				library. I later modified the initial entry to add in some different weapons and bullet patters. You can see 
				a video of the weapons below<br>
				<a href='http://projects.thegupstudio.com/repulsor.exe'>Download original</a><br>
				<object width='425' height='344'><param name='movie' 
					value='http://www.youtube.com/v/zSRjiBzhKzA&hl=en&fs=1&rel=0'></param>
					<param name='allowFullScreen' value='true'></param>
					<param name='allowscriptaccess' value='always'></param>
					<embed src='http://www.youtube.com/v/zSRjiBzhKzA&hl=en&fs=1&rel=0' type='application/x-shockwave-flash' 
					allowscriptaccess='always' allowfullscreen='true' width='425' height='344'></embed></object>
				""",
        },
		{		"title":'phpBB Image Archive',
				"short":'Automatically archive any posted images',
				"imgSrc":'/site_media/images/project/phpbb_logo.png',
				"cat":'Tools',
				"tag":"phpbb_archiver",
				"info":"""I developed this script while running a phpBB based art community. As many images that are posted on a forum are 
				 linked from temporary hosting locations, old discussions tend to lose coherency. By automatically saving a copy of the linked images 
				 to another location, the posts and the art they contain are saved. This is a php script that is designed to be run by cron. Each time 
				 it runs, it scans all new posts for any images. It then saves the images it finds, and ftp's them over to a specified account, where it
				  organizes the files by poster id, and post id. In the phpBB template, I've added a 'view archived' link under each post that can then 
				  pull up any images that have been saved for that post
				  <br>
				  <b>Technologies: </b>PHP, MySQL, FTP
				  """,
		},
		{		"title":'Nibbles - game',
				"short":'2d platformer collaboration for Global Game Jam',
				"cat":'Games',
				"tag":"nibbles",
				"imgSrc":'/site_media/images/project/nibbles_icon.png',
				"info":"""Nibbles was a group project made during the course of a 48 Global Game Jam compitetion. The game
				is made in Flash using 3D backgrounds rendered into 2D. I was one of two programmers on the team.
				<br>
				<b>Technologies:</b> Flash using Flixel, Kongregate API. Perl+MySQL score server<br>
				You can view the team members on <a href='http://globalgamejam.org/2010/white-lies-0'>the game jam entry</a>
				<br>
				Nibbles is <a href='http://www.kongregate.com/games/SokerCap/nibbles/'>live on Kongregate</a>
				  """,
		},
		{		"title":'WAS Fighter',
				"short":'2d arcade style fighting game',
				"cat":'Games',
				"tag":"was_fighter",
				"imgSrc":'/site_media/images/project/was_brunks.png',
				"info":"""WAS Fighter is originally a 2d fighting game with the art and characters as a 
				community work from Webcomic Artists Society. It was written in C++ with DirectX but was 
				never finished and may get rewritten as an XNA game.
				<br>
				<b>Technologies:</b> C++, DirectX<br>
				<a href='http://projects.thegupstudio.com/fighter/cast.html'>Cast of Characters</a><br>
				<a href='http://projects.thegupstudio.com/fighter/downloads/latestbuild.rar'>Movement and Character Selection demo</a>
				<br><i>above does not include the DirectX installer. If you need it, download 
				<a href='http://projects.thegupstudio.com/fighter/downloads/d3dx9__26.dll'>d2dx9_26.dll</a> here
				""",
		},
		{		"title":'Drifting on Stellar Winds',
				"short":'2D space exploration browser MMO',
				"tag":"drifting",
				"cat":'Games',
				"imgSrc":'/site_media/images/project/drift_neutron.png',
				"info":"""Drifting on Stellar Winds was prototyped during the last <a href='http://ludumdare.org'>Ludum 
				Dare</a> 48 hour competition but quickly grew in scope. It is designed as a 2d top down space game 
				with an emphasis on exploration and procedurally generated universes and ai's. Solar radiation from 
				nearby stars and solar bodies generate currents that players can utilize to manuever around. 
				<br>
				<b>Technologies:</b>Flash, Javascript, Perl, MySQL, Python, Drupal, AppEngine<br>
				<a href='http://play.drifting.thegup.com'>Test out Drifting</a><br>
				""",
		},
		{		"title":'Misc. Scripts',
				"tag": "misc_scripts",
				"short":'assorted small programs',
				"cat":'Misc',
				"imgSrc":'/site_media/images/project/misc_anna.png',
				"info":"""
					<ul>
					<li><a href='http://thegupstudio.com/samples/Hyperspace.html'>Hyperspace demo</a> - 
						Using Flash and Away3d to generate a fake hyperspace effect. Rotates a large cone around the camera 
						and moves the texture. Arrows or wasd to move, space to fire.
					</li>
					<li><a href='http://thegupstudio.com/samples/lolbike.html'>Flash racing</a> - 
						Testing road effects in Flash in an attempt to make a road rash clone.
					</li>
					<li><a href='http://thegupstudio.com/was_irc/commands.html'>MockerBot</a> - 
						An irc chatbot built up from Net::IRC in Perl with many custom modules added. Can parse equations, 
						do basic conversation responses, run a game of battleship, parse information from many different 
						websites and more.
					</li>
					<li><a href='http://thegupstudio.com/scripts/memegen.cgi'>Meme Generator</a> - 
					Simple mashup that takes a random image from livejournal and pairs it up with madlibs style 
					memes. <b>NSFW</b> . Because the images are random and not moderated they may be nsfw.
					</li>
					</ul>
				""",
		},
		]
	return render_to_response('projects.html',{
	'projects':fake_model, 
	'projects_size': len(fake_model)*115
	})

def showcase(request):
	fake_model = [
		{	"title":'Web Sites',
			"projects": [
			{
				"title":"RyanGuthrie.com",
				"thumbSrc":"/site_media/images/portfolio/rg_icon.png"
			},
			{
				"title":"Free Photo Project",
				"thumbSrc":"/site_media/images/portfolio/freephoto_icon.png"
			},
			]
		},
		{	"title":'Games',
			"projects": [
			{
				"title":"RyanGuthrie.com",
				"thumbSrc":"/site_media/images/portfolio/rg_icon.png"
			},
			{
				"title":"Free Photo Project",
				"thumbSrc":"/site_media/images/portfolio/freephoto_icon.png"
			},
			]
		},
		{	"title":'Misc',
			"projects": [
			{
				"title":"RyanGuthrie.com",
				"thumbSrc":"/site_media/images/portfolio/rg_icon.png"
			},
			{
				"title":"Free Photo Project",
				"thumbSrc":"/site_media/images/portfolio/freephoto_icon.png"
			},
			]
		},
		]
	return render_to_response('showcase.html',{
	'showcase':fake_model, 
	'projects_size': len(fake_model)*115
	})


def projectData(request):
	msg = '';

	return HttpResponse(msg)